name: Common-Actions

on:
  push:
    branches: [ main ]

jobs:
  test:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-go@v2
        with:
         go-version: '^1.14'
      - run: go version
         
      - name: Test
        run: go test ./...
    
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: ls -la
