name: Common-Actions

on:
  push:
    branches: [ main ]

jobs:
  test:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: variantdev/setup-go-actions@v1
      - run: actions -help
         
      - name: Test
        run: go test ./...
    
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: ls -la
